Text Reader Improvement Added
apu52/METAVERSE pull request #1209
Opened 2024-08-04 15:50 UTC by Damini2004

# Title and Issue number 

Title : Text Reader Improvement Added

Issue No. : #1172 

Code Stack : HTML, CSS

Close #1172

# Video (mandatory)

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

- [x] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor

2024-08-04 15:59 UTC, Damini2004 commented
#1210 #1211 Kindly assign this to me. @apu52

2024-08-05 13:33 UTC, apu52 requested changes
please do the necessary changes , otherwise the other changes are really good

2024-08-05 13:33 UTC, apu52 commented on Projects/Text-Reader/index.html
> +    <title><strong><u>Text Reader</u></strong></title>
why this <strong><u> present here in the name , it looks odd

2024-08-05 13:35 UTC, apu52 commented on Projects/Text-Reader/index.html
> +    <title><strong><u>Text Reader</u></strong></title>
![image](https://github.com/user-attachments/assets/d6da2425-1c0b-4990-8b95-4e09985485c2)

2024-08-05 15:15 UTC, Damini2004 commented
@apu52 Changes resolved.

2024-08-06 13:46 UTC, apu52 approved these changes
@Damini2004 good work

2024-08-06 13:46 UTC, merged