added signup login page
apu52/METAVERSE pull request #1387
Opened 2024-12-22 14:20 UTC by Nishakulkarni06

# Title and Issue number 

Title : Added Signup Login Page

Issue No. :#1386

Tech Stack : HTML,CSS,JS

# Type of PR

- [x] Feature enhancement
- [x] Documentation update
 
# Video (mandatory)

Uploading METAVERSE and 5 more pages - Profile 1 - Microsoft​ Edge 2024-12-22 19-48-20.mp4…

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have gone through the  `contributing.md` file before contributing
- [x] I have Starred the Repository.

# Checklist:(In case of Adding New WEB3 project only)

- [ ] I have made my Commits(of new project) under the  `Projects` folder
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] i have added the image of my project under `asstes/img` folder

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

- [x] I'm a KWOC 2024 contributor

2024-12-27 12:18 UTC, apu52 requested changes
@Nishakulkarni06 the whole design & the functionalities are well defined , but try to make a button in the navbar like login & the after user clicks on it try to make a separate login page for it & after login redirect the user in the home page , 

& also try to make the login page UI more compatible with the website

2024-12-27 12:19 UTC, apu52 commented
@Nishakulkarni06 if u will need any type of help in this feature adding feel free to reach out to me

2024-12-29 18:25 UTC, Nishakulkarni06 commented
ok

2024-12-31 11:26 UTC, Nishakulkarni06 commented
But the thing is Home page is accessible only after login so should i display like circle in profile in navbar?

2025-01-11 04:28 UTC, apu52 commented
> But the thing is Home page is accessible only after login so should i display like circle in profile in navbar?

yess u can

2025-01-12 17:18 UTC, Nishakulkarni06 commented
@apu52  I have made changes .

2025-03-20 01:22 UTC, closed without merging