Tiktok Clone Added
apu52/METAVERSE pull request #317
Opened 2023-12-18 15:12 UTC by aindree-2005

# Title and Issue number 

Title : Tiktok clone

Issue No. : #305 

Code Stack : html,css,js

Close #305

# Video (mandatory)

[video (1).webm](https://github.com/apu52/METAVERSE/assets/68018372/94446ebe-6a32-42bc-9fac-7aa54dccdbf2)

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have updated the `projectData.json` file for my contribution
- [x] I have added the img of my project in the `assets/img` section

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

CodePeak, KWOC

2023-12-18 15:40 UTC, apu52 requested changes
This file is not needed for this PR. Please make sure that you make PR in all different branches in your forked repo

2023-12-18 16:06 UTC, aindree-2005 commented
> This file is not needed for this PR. Please make sure that you make PR in all different branches in your forked repo

@apu52 deleted those sorry

2023-12-18 18:36 UTC, apu52 approved these changes
ok

2023-12-18 18:37 UTC, merged

2023-12-19 03:58 UTC, shruti-sen2004 commented
@aindree-2005 due to some issue we had to delete your previous merge. Can you please add your project once again to our repo. No need to make a issue for that just make the PR with necessary files. Also you wont be getting extra points for this as you have been awarded points for the both the issue and PR.

Thank you,
Shruti Sen