Family Travel Tracker
apu52/METAVERSE pull request #482
Opened 2023-12-25 10:29 UTC by singhcoder694

# Title and Issue number 
Title : Family Tracker
Issue No. : #459

Code Stack : 
- HTML, CSS
- EJS
- NODE & EXPRESSJS
- postGRE SQL

Close #459

# Video (mandatory)

https://github.com/apu52/METAVERSE/assets/114601400/ff38aff8-dfb5-41cb-adc3-7b8a75117664

# Checklist:

- [ ] I have mentioned the issue number in my Pull Request.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have updated the `projectData.json` file for my contribution
- [ ] I have added the img of my project in the `assets/img` section

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

2023-12-26 11:01 UTC, apu52 commented
@singhcoder694 Please attach a proper README.md file with this project.

2023-12-26 11:01 UTC, apu52 requested changes
Readme.md?

2023-12-27 06:32 UTC, singhcoder694 commented
@apu52 updated README and resolved conflicts

2023-12-27 18:51 UTC, apu52 approved these changes

2023-12-27 18:52 UTC, merged