Complete and Enhance the Home Page for Netflix Clone( DONE)
apu52/METAVERSE pull request #801
Opened 2024-06-16 16:43 UTC by shreya-2410

# Title and Issue number 

Title :Complete and Enhance the Home Page for Netflix Clone #791 

Issue No. :#791

Code Stack : html and css

Close #791 

# Video (mandatory)

Uploading bandicam 2024-06-16 22-00-30-935.mp4…

# Checklist:

- [ x] I have mentioned the issue number in my Pull Request.
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [x ] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**
it is my time contributing hence i could not put readme file but be assured code is easy to understand and have tried my best to clone original netflix ui.

***Are you contributing under any Open-source programme?***

- [ ] I'm a GSSOC'24 contributor
- [ x] I'm a SSOC'24 contributor

2024-06-22 13:55 UTC, vHarshita15 commented
Want to work on this issue . Plese assign

2024-06-22 15:35 UTC, apu52 requested changes

2024-06-22 15:35 UTC, apu52 commented on Projects/Netflix_clone_Project/index.js
@shreya-2410 Why this full JS file has been removed & I also can see there is a massive UI change for the Project . Can u please share a video that how many additional features iu have added in this project?? 
Please attach a video with this pR

2024-07-05 13:47 UTC, shreya-2410 commented
https://github.com/apu52/METAVERSE/assets/137192044/e4dff513-4bad-4791-a56b-2b3063771c1f

here is the video of the clone before vs after ..actually i have tried my best enhancing the clones ui ...i have not made it functional by using js ..but changed its appearance completely and hence to avoid any glitches i have removed js file ...

2024-07-05 13:53 UTC, apu52 approved these changes
@shreya-2410 okk

2024-07-05 13:54 UTC, merged

2024-07-05 14:14 UTC, shreya-2410 commented
why are my points not reflecting on oslead website

2024-07-05 15:49 UTC, apu52 commented
> why are my points not reflecting on oslead website

I have already added your points & it has been successfully added Can u please check now??

2024-07-05 15:49 UTC, apu52 commented
![image](https://github.com/apu52/METAVERSE/assets/114172928/cfb8fa6a-c46a-4ebd-8e57-efc6c46b5b78)

here at rank 7