Fix issues and make improvements
apu52/METAVERSE pull request #808
Opened 2024-06-17 16:48 UTC by MetiUmashri

# Title and Issue number 
Title : Age Calculator Not Working

Issue No. : 779

Code Stack : 

Close #<issue_no>

# Video (mandatory)

# Checklist:

- [ ] I have mentioned the issue number in my Pull Request.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

- [ ] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor

2024-06-21 16:27 UTC, MetiUmashri commented
@apu52 kindly merge this enhancement

2024-06-22 15:45 UTC, apu52 requested changes
please do the changes above mentioned so that I can merge the PR

2024-06-22 15:45 UTC, apu52 commented on Projects/Age_Calculator/script.js
@MetiUmashri the changes u have made are really good

2024-06-22 15:45 UTC, apu52 commented on Projects/Age_Calculator/style.css
@MetiUmashri please add the BG img . So that it will be easier for the users to use this . Please make the changes

2024-06-23 11:26 UTC, closed without merging